export default {
  LOAD_COUNTRIES_REQUEST: '@@countries/LOAD_COUNTRIES_REQUEST',
  LOAD_COUNTRIES_SUCCESS: '@@countries/LOAD_COUNTRIES_SUCCESS',
  LOAD_COUNTRIES_FAILURE: '@@countries/LOAD_COUNTRIES_FAILURE',
}
